name: "Set version"
description: "Sets the version property of the apax.yml to the provided version"
inputs:
  version:
    description: "The version to set in the apax.yml"
    required: true
  path:
    description: "The relative path to the project which is to be built"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Set version
      shell: bash
      run: |
        
        version_regex="^([0-9]+)\.([0-9]+)\.([0-9]+)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$"

        # Check version against regex expression
        if [[ ${{ inputs.version }} =~ $version_regex ]]; then
          echo "The version ${{ inputs.version }} is compliant to semantic versioning."
        else
          echo "Error: The version ${{ inputs.version }} is not compliant to semantic versioning."
          exit 1
        fi

        # Change to the project directory
        cd ${{ inputs.path }}
        
        # built command
        CMD="apax set-version --version ${{ inputs.version }}"
        
        # execute command
        echo "Running command: $CMD"
        eval $CMD