name: Distribute common files

on:
  workflow_dispatch: {} #to enable manual triggering of the action
  inputs:
    repo_name:
      description: |
        You can specify name of the repository where workflows should be pushed manually. As long as repository is not ignored by workflow settings.
        If you do not specify exact repository name, the workflow will try to replicate all missing changes to all repositories.
      required: true
jobs:
  deploy_common_file:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Replicating global workflow
          uses: derberg/manage-files-in-multiple-repositories@v2
          with:
            github_token: ${{ secrets.DEPLOY_KEY }}
            patterns_to_include: files/libraries/workflows/release-library.yml, files/libraries/workflows/lint-repo.yml, files/libraries/workflows/build-library.yml
            destination: .github/workflows
            topics_to_include: library
            exclude_private: false
            exclude_forked: true
            committer_username: simatic-ax-bot
            commit_message: "ci: distribute workflows for libraries"
  
