name: "Setup the apax environment"
description: "Installs apax and needed software on the runner in order to test, build, pack and release apax packages"
inputs:
  APAX_TOKEN:
    required: true
    description: "The access token is used to log into the apax registry in order to retrieve apax npm package"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "No cache hit, setup from scratch"
        
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
          
    - name: install_apax
      shell: bash
      env:
        APAX_TOKEN: ${{ inputs.APAX_TOKEN }}
        SCRIPT_PATH: actions
      run: |
        sudo apt-get install --assume-yes --no-install-recommends \
        libtinfo6 \
        ls
        cd /usr/local/lib/
        ls
        ln -s /usr/local/lib/libtinfo.so.6 /usr/local/lib/libtinfo.so.5
        git 
        npm -v
        node -v
        sudo mkdir apax-dep
        sudo npm config set prefix "~/.local/"
        sudo mkdir -p ~/.local/bin
        sudo echo 'export PATH=~/.local/bin/:$PATH' >>~/.bashrc
        sudo npm init -y
        sudo curl -f -H "Authorization: bearer $APAX_TOKEN" https://api.simatic-ax.siemens.io/apax/login?format=npmrc > .npmrc
        sudo npm add @ax/apax-signed
        sudo npm install
        cd node_modules/@ax/apax-signed
        ls -al
        sudo chmod 777 .
        echo "-----BEGIN PUBLIC KEY-----" \
        >public.pem
        sudo echo "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4m2LqXil8zyn+Z9v0J93" \
        >>public.pem
        echo "03hNjjrw6JMKvj0skNJvSaNPq1cYwq1Q/cu86Ny/Wl+lJT+Nzl32oKcgPuU+eY1Z" \
        >>public.pem
        echo "VTm9ZYPmIuoO+WPEsW5v1q8u7LURJt5jMxyfVQLXakUzkrjdQY+8/fO77R/s7ndi" \
        >>public.pem
        echo "qOXvoDw4SC8RAcbFVoske7R9L8nr8+lAjyOAs7fcWEOAkXaFF3BNIddxAGtAjXr5" \
        >>public.pem
        echo "5y+ecHh0wom+diN3RdSDk5TqKl9F8lThAqd8LjFxRcjaeaKftruTB9yd+ppN/4wl" \
        >>public.pem
        echo "avwaTQ/7eYHbvNV5aYeELUzxFykhsqKlIeo93y/ncnU0xS7W6ccCvNJ74kRfRtJY" \
        >>public.pem
        echo "WwIDAQAB" \
        >>public.pem
        echo "-----END PUBLIC KEY-----" \
        >>public.pem
        npm install --global ax-apax-*.tgz --verbose
        apax --version
