name: "Building an apax library or application"
description: "Builds the package and returns it as an artifact"
inputs:
  APAX_TOKEN:
    required: true
    description: "The access token is used to log into the apax registry in order to retrieve apax npm package"

runs:
  using: "composite"
  steps:
    - name: "Checkout actions repository"
      uses: actions/checkout@v3
      with:
        path: _repo

    - name: Switch working directory
      shell: bash
      run: cd _repo

    - name: Login to apax repository
      run: apax login --password ${{ inputs.APAX_TOKEN }}
      shell: bash

    - name: Install apax dependencies
      run: apax install --update-lockfile
      shell: bash

    - name: Build apax package
      shell: bash
      run: apax build --coverage
