name: "Testing an apax library or application"
description: "Tests the packages binaries and returns it as an artifact"
inputs:
  library-directory:
    required: true
    description: "The access token is used to log into the apax registry in order to retrieve apax npm package"
  apax-access-token:
    required: true
    description: "The access token is used to log into the apax registry in order to retrieve apax npm package"

runs:
  using: "composite"
  steps:
    - name: Cache apax install
      id: cache-apax
      uses: actions/cache@v3
      with:
        path: |
          $GITHUB_WORKSPACE/.apax
        key: ${{ runner.os }}-apax--${{ hashFiles('**/apax.yml') }}

    - name: Login to apax repository
      run: apax login --password ${{ inputs.apax-access-token }}
      shell: bash

    - name: Install apax dependencies
      run: apax install
      shell: bash

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: build
        path: $GITHUB_WORKSPACE/bin/

    - run: |
        ls bin
      shell: bash

    - name: Build apax package
      shell: bash
      run: apax test
