name: "Lint commit"
description: "Lints a commit message and checks if it is conformant to conventional commit"
inputs:
  commit-message: # id of input
    description: "Commit message to be linted"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: setup_node
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: lint commit message
      shell: bash
      run: |
        npm install --save-dev @commitlint/config-conventional @commitlint/cli
        echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
        npx commitlint ${{ inputs.who-to-greet }} --strict --config "./commitlint.config.js"
