name: "Lint repository"
description: "Lints files and directories with repolinter, checking for required files e.g. documentation and readme"

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Check markdown files
      uses: avto-dev/markdown-lint@v1
      with:
        args: "**/*.md"
        ignore: ./LICENSE.md
