name: "Templatify repository"
description: "Clones the given repository and creates an apax template out of it"
inputs:
  repository-url:
    description: "The URL of the repository to templatify"
    required: true
  token:
    description: "The token to use for cloning the repository"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository-url }}
        token: ${{ inputs.token }}
      
    - name: Debug step
      run: ls -a
