name: "Templatify repository"
description: "Clones the given repository and creates an apax template out of it"
inputs:
  path:
    description: "The directory to work in"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Templatify
      shell: bash
      run: |
        echo "Your starting point"
        ls -a -1
        # adapt the lib/ app to the template structure
        echo "adapt the lib/ app to the template structure"
        
        echo ${{ inputs.path }}
        cd ${{ inputs.path }}
        echo "Your're currently working here"
        ls -a -1

        # extract original name
        apax_file="apax.yml"
        original_name=$(grep '^name:' "$apax_file" | awk -F ': ' '{print $2}' | tr -d '"')
        original_name=${original_name#@simatic-ax/}
        
        # carve out unnecessary files and folders
        # Pfad zur Datei templatify-meta-information.yml
        META_INFO_FILE="templatify-meta-information.yml"

        # Extrahiere die Liste der Dateien und Ordner aus der Datei
        ALLOWED_PATHS=($(awk '/^files:/ {flag=1; next} /^[^ ]/ {flag=0} flag && /^\s*- / {sub(/^\s*- /, ""); print}' "$META_INFO_FILE"))

        # Debugging: Überprüfe, ob ALLOWED_PATHS korrekt gefüllt ist
        echo "Extrahierte Pfade:"
        for path in "${ALLOWED_PATHS[@]}"; do
            echo "$path"
        done
        

        # include newly to be created CHANGELOG.md