name: "Version an apax project and pack for release"
description: "Versions and pack for release"
inputs:
  VERSION:
    required: true
    description: "Semantic version for the newly created package"
  APAX_TOKEN:
    required: true
    description: "The access token is used to log into the apax registry in order to retrieve apax npm package"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        apax version ${{ inputs.VERSION }}
