name: "Lint repository"
description: "Lints files and directories with repolinter, checking for required files e.g. documentation and readme"

runs:
  using: "composite"
  steps:
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: install repolinter
      shell: bash
      run: |
        echo "Installing repolinter"
        npm install --global repolinter

    - name: "checkout repo"
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 0
        path: _repolint

    - name: "Run linter"
      shell: bash
      run: |
          FILE=/home/runner/work/ae-trafficlight/ae-trafficlight/_repolint/repolint.json
          if [ -f "$FILE" ]; then
              echo "Execute the local settings file from the repository"
              repolinter lint _repolint
          else 
              echo "Execute the general settings"
              repolinter lint _repolint --rulesetUrl https://raw.githubusercontent.com/simatic-ax/actions/refs/heads/test_repo_lint_fabian_unglert/lint-repository/repolint.json
          fi