name: "Lint repository"
description: "Lints files and directories with repolinter, checking for required files e.g. documentation and readme"

runs:
  using: "composite"
  steps:
    - name: "checkout repo"
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 0

    - name: Run linter
      uses: philips-labs/github-action-repolinter@master
      env:
        CUSTOM_REPOLINT_FILE: repolint.json
