name: "Install dependencies"
description: "Installs the dependencies and devDependencies based on the projects apax.yaml file"
inputs:
  immutable:
    description: "Install all dependencies and devDependencies from the apax-lock.json or throw if not there or not in sync with your apax.yml"
    required: false
    default: "false"
  catalog:
    description: "Installs dependencies according to catalog"
    required: false
    default: "false"
  strict:
    description: "Applies the exact package versions from the catalog"
    required: false
    default: "false"
  path:
    description: "The relative path to the project whose dependencies are to be installed"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install apax dependencies
      shell: bash
      run: |

        # Change to the project directory
        cd ${{ inputs.path }}

        # base command
        cmd="apax install"

        # Check the inputs and add the corresponding flags to the command
        if [[ "${{ inputs.immutable }}" == "true" ]]; then
          echo "Info: Add --immutable to cmd"
          cmd+=" --immutable"
        fi

        if [[ "${{ inputs.catalog }}" != "false" ]]; then
          echo "Info: Add --catalog to cmd"
          cmd+=" --catalog ${{ inputs.catalog }}"
          if [[ "${{ inputs.strict }}" == "true" ]]; then
            echo "Info: Add --strict to cmd"
            cmd+=" --strict"
          fi
        elif [[ "${{ inputs.strict }}" == "true" ]]; then
          echo "Error: The --strict flag can only be used with the --catalog flag."
          exit 1
        fi

        if [[ "${{ inputs.verbose }}" == "true" ]]; then
          echo "Info: Add --verbose to cmd"
          cmd+=" --verbose"
        fi

        echo "Running command: $cmd"
        eval "$cmd"
  