name: apax-publish
on:
  workflow_call:
    secrets:
      APAX_TOKEN:
        description: "Access token for installing apax sdk"
        required: true
      DEPLOY_KEY:
        description: "Key for logging into the github registry"
        required: true
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Setup the apax runner"
        uses: simatic-ax/actions/setup-apax-runner@kruegerf-feat-reusable
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Fetch clog"
        run: |
          curl -L https://github.com/clog-tool/clog-cli/releases/download/v0.9.3/clog-v0.9.3-x86_64-unknown-linux-gnu.tar.gz > clog.tar.gz 
          tar -xvf ./clog.tar.gz
          chmod +x ./clog
          ./clog -V
          ./clog --from $( git tag -l | head -2 | tail -1 ) --setversion ${{ inputs.VERSION }}

      - name: "Login to the private repo"
        run: |
          apax login --registry "https://npm.pkg.github.com" --password "${{ secrets.DEPLOY_KEY }}"

      - name: "Build the apax workspace"
        uses: simatic-ax/actions/apax-build@kruegerf-feat-reusable
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Pack and publish the library"
        run: |
          apax version "${{ inputs.VERSION }}"
          apax pack 2>.package.err 1>.signature
          PACKAGE="$(grep -oP '(?<=\").+.apax\.tgz(?=\")' .package.err)"
          apax publish --package $PACKAGE --registry https://npm.pkg.github.com
