name: apax-build
on:
  workflow_call:
    secrets:
      APAX_TOKEN:
        description: "Access token for installing apax sdk"
        required: true
      SIMATIC_AX_TOKEN:
        description: "Access token for installing packages from github registry, required if LOGIN_SIMATIC_AX is true"
        required: false
    inputs:
      ACTIONS_REF:
        required: false
        type: string
        default: release
      LOGIN_SIMATIC_AX:
        type: boolean
        default: false

jobs:
  build:
    env:
      ACTIONS_TARGET_PATH: "actions"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Setup the apax runner"
        uses: simatic-ax/actions/setup-apax-runner@stable
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Login to simatic-ax registry"
        if: ${{ inputs.LOGIN_SIMATIC_AX }}
        run: |
          apax login --registry "https://npm.pkg.github.com" --password "${{ secrets.SIMATIC_AX_TOKEN }}"

      - name: "Build the apax workspace"
        uses: simatic-ax/actions/apax-build@stable
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Upload the build artifact"
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: bin/
