name: apax-publish-application-example
on:
  workflow_call:
    secrets:
      APAX_TOKEN:
        description: "Access token for installing apax sdk"
        required: true
      DEPLOY_KEY:
        description: "Key for logging into the github registry"
        required: true
    inputs:
      VERSION:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup the apax runner"
        uses: simatic-ax/actions/setup-apax-runner@stable
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Fetch clog"
        run: |
          curl -L https://github.com/clog-tool/clog-cli/releases/download/v0.9.3/clog-v0.9.3-x86_64-unknown-linux-gnu.tar.gz > clog.tar.gz 
          tar -xvf ./clog.tar.gz
          chmod +x ./clog
          ./clog -V
          ./clog --from $( git tag -l | head -2 | tail -1 ) --setversion ${{ inputs.VERSION }} > changelog
          cat ./changelog

      - name: "Login to the private repo"
        run: |
          apax login --registry "https://npm.pkg.github.com" --password "${{ secrets.DEPLOY_KEY }}"

      - name: "Create an empty template to receive the application example"
        run: |
          mkdir simatic-ax-${{ inputs.PROJECT_NAME }}
          cd simatic-ax-${{ inputs.PROJECT_NAME }}
          mkdir template
          VERSION=${{ inputs.VERSION }}
          echo name: "'@simatic-ax/template-${{ inputs.PROJECT_NAME }}'" >> apax.yml
          echo version: $VERSION >> apax.yml
          echo type: generic >> apax.yml
          cat apax.yml
          # files section will be created in the "pack" step
          cd ..

      - name: "Clone the application example repository into the template folder"
        uses: actions/checkout@v3
        with:
          path: ./simatic-ax-${{ inputs.PROJECT_NAME }}/template

      - name: "Pack and publish the application example"
        run: |
          cd ./simatic-ax-${{ inputs.PROJECT_NAME }}
          cat ./template/apax-files-section.yml >> ./apax.yml
          cat apax.yml
          apax pack 2>.package.err 1>.signature
          apax pack 2>.package.err 1>.signature
          echo "pack done"
          PACKAGE="$(grep -oP '(?<=[\s\"])[a-z0-9.-_]+.apax\.tgz' .package.err)"
          echo "package name: $PACKAGE"
          apax publish --package $PACKAGE --registry https://npm.pkg.github.com
          echo "pack done"