name: apax-build
on:
  workflow_call:
    secrets:
      APAX_TOKEN:
        description: "Access token for installing apax sdk"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout actions repository"
        uses: actions/checkout@v3
        with:
          repository: simatic-ax/actions
          ref: "kruegerf-feat-reusable"
          fetch-depth: 1
          path: actions

      - name: "Setup the apax runner"
        uses: ./actions/.github/actions/setup-apax-runner
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Build the apax workspace"
        uses: ./actions/.github/actions/build-apax-package
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Upload the build artifact"
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: bin/
