name: "Check repository"

on: workflow_call

jobs:
  repolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: "kruegerf-feat-reusable"
      - name: list files
        shell: bash
        run: ls -al
      - name: "Run repolinter"
        uses: ./.github/actions/lint-repository

  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: "kruegerf-feat-reusable"

      - name: "Run markdownlinter"
        uses: ./.github/actions/lint-markdown
