name: "Check repository"

on: workflow_call

jobs:
  repolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: "Run repolinter"
        uses: ./.github/actions/lint-repository

  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: "Run markdownlinter"
        uses: ./.github/actions/lint-markdown
