name: "Check repository"

on: workflow_call

jobs:
  repolint:
    runs-on: ubuntu-24.04
    steps:
      - name: "Run repolinter"
        uses: simatic-ax/actions/lint-repository@stable

  markdownlint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Run markdownlinter"
        uses: simatic-ax/actions/lint-markdown@stable
