name: "Check repository"

on: workflow_call

jobs:
  repolint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout actions repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Run repolinter"
        uses: simatic-ax/actions/.github/actions/lint-repository

  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: simatic-ax/actions
          ref: kruegerf-feat-reusable
          fetch-depth: 1
          path: actions

      - name: "Run markdownlinter"
        uses: ./actions/.github/actions/lint-markdown
