# This workflow is going to be used during the development phase of the project
# The workflow builds and tests the the sources on the following triggers:
#   - once a change is pushed to the main branch or any of its sub-branches
name: Development Workflow

on:
  push:
    branches:
      - 'main'
      - 'main/**'
  pull_request:
    branches:
      - 'main'
      - 'main/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.4.2
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug output
        run: ls -a
      - name: Login to required registries
        uses: ./apax-login # replace with simatic-ax/actions/apax-login@v1
        with:
          apax-token: ${{ secrets.APAX_TOKEN }}
          registries: |
            https://npm.pkg.github.com/,${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        uses: ./apax-install # replace with simatic-ax/actions/apax-install@v1
        with:
          path: actions-test

      # - name: Build source code
      #   uses: ./build # replace with simatic-ax/actions/build@v1
      #   with:
      #     APAX_TOKEN: ${{ secrets.APAX_TOKEN }}