# This workflow is going to be used during the development phase of the project
# The workflow builds and tests the the sources on the following triggers:
#   - once a change is pushed to the main branch or any of its sub-branches
name: Development Workflow

on:
  push:
    branches:
      - 'main'
      - 'main/**'
  pull_request:
    branches:
      - 'main'
      - 'main/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.4.2
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to required registries
        uses: ./apax-login # replace with simatic-ax/actions/apax-login@v1
        with:
          apax-token: ${{ secrets.APAX_TOKEN }}
          registries: |
            https://npm.pkg.github.com/,${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        uses: ./apax-install # replace with simatic-ax/actions/apax-install@v1
        with:
          path: actions-test

      - name: Build source code
        uses: ./apax-build # replace with simatic-ax/actions/apax-build@v1
        with:
          path: actions-test
          apax-build-targets: |
            llvm
            1500
          apax-build-args: |
            --debug
            --log Debug
      
      - name: Test source code
        uses: ./apax-test # replace with simatic-ax/actions/apax-test@v1
        with:
          path: actions-test
          coverage: true
          loglevel: debug

      - name: Package source code
        uses: ./apax-pack # replace with simatic-ax/actions/apax-pack@v1
        with:
          path: actions-test
      
      - name: Publish apax package
        uses: ./apax-publish # replace with simatic-ax/actions/apax-publish@v1
        with:
          registries: |
            https://npm.pkg.github.com
          tag: latest
          path: actions-test

