name: Release Workflow

on:
  push:
    branches:
      - "release/**"
  workflow_dispatch:  # Ermöglicht manuelles Triggern des Deploy-Schritts

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.4.2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: echo "Installing dependencies"

      - name: Build Project
        run: echo "Building project"

  test:
    name: Test
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.4.2
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: echo "Installing dependencies"

      - name: Run Tests
        run: echo "Running tests"

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.4.2
    needs: test
    if: github.event_name == 'workflow_dispatch'  # Nur bei manuellem Trigger
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: echo "Deploying application..."
