name: package-on-release
on: 
  push:
    branches:
      - main

jobs:
  test:
    name: "Test apax"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup apax
        uses: ./.github/actions/setup-apax-runner
        with:
          apax-access-token: ${{ secrets.APAX_ACCESS_TOKEN }}
      
      - name: Assert apax installation
        run: |
              apax --version
    
