# This workflow is going to be used for a release of a library
# The workflow builds, tests and publishes the package
# Publishing a package needs to be done manually
name: Library release workflow
on:
    workflow_dispatch:
    push:
        branches:
        - 'main'
        - 'main/**'
    pull_request:
        branches:
        - 'main'
        - 'main/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.4.2
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to required registries
        uses: ./apax-login # replace with simatic-ax/actions/apax-login@v3
        with:
          apax-token: ${{ secrets.APAX_TOKEN }}
          registries: |
            https://npm.pkg.github.com/,${{ secrets.DEPLOY_TOKEN }}

      - name: Install dependencies
        uses: ./apax-install # replace with simatic-ax/actions/apax-install@v3
        with:
          path: actions-test

      - name: Build source code
        uses: ./apax-build # replace with simatic-ax/actions/apax-build@v3
        with:
          path: actions-test
          apax-build-targets: |
            llvm
            1500
          apax-build-args: |
            --debug
            --log Debug
      
      - name: Test source code
        uses: ./apax-test # replace with simatic-ax/actions/apax-test@v3
        with:
          path: actions-test
          coverage: true
          loglevel: debug

      - name: Package source code
        uses: ./apax-pack # replace with simatic-ax/actions/apax-pack@v3
        with:
          path: actions-test # remove

      - name: Publish apax package
        uses: ./apax-publish # replace with simatic-ax/actions/apax-publish@v3
        with:
          registries: |
            https://npm.pkg.github.com
          tag: latest
          path: actions-test

