name: "Check repository"

on: workflow_call
jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout actions repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Run markdownlinter"
        uses: simatic-ax/actions/lint-commit@stable
        with:
          commit-message: ${{ github.event.head_commit.message }}
