name: "Check repository"

on: workflow_call
jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout actions repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: "Checkout actions repository"
        uses: actions/checkout@v3
        with:
          repository: simatic-ax/actions
          ref: "kruegerf-feat-reusable"
          fetch-depth: 1
          path: actions

      - name: "Run markdownlinter"
        uses: ./actions/.github/actions/lint-commit
        with:
          commit-message: ${{ github.event.head_commit.message }}
