# This workflow is triggered when a release is published via the UI
# The workflow is only executed if the release is a tag and the target_commitish is a release branch
name: Release workflow

# Start the workflow as soon as a release has been published via the UI
on:
  release:
    types: [published]

jobs:
  call-development:
    name: Build the package
    if: ${{ true }}
    uses: ./.github/workflows/package-development-workflow.yml
    secrets:
      APAX_TOKEN: ${{ secrets.APAX_TOKEN }}
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
    with:
      ref: ${{ github.ref }}
  release:
    name: Release the package
    needs: call-development
    # Only run the workflow if the release is a tag and the target_commitish is a release branch
    # Matching the correct branch is being done using naming conventions
    if: ${{ true }}
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.4.2
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: bin
          
      - name: Version package
        uses: ./apax-version # replace with simatic-ax/actions/apax-version@v3
        with:
          version: ${{ github.event.release.tag_name }}
          path: actions-test # remove later, for test purposes only
  
      - name: Package source code
        uses: ./apax-pack # replace with simatic-ax/actions/apax-pack@v3
        with:
          key: ${{ secrets.APAX_SIGNKEY }}
          path: actions-test # remove later, for test purposes only
          
      - name: Login to required registries
        uses: ./apax-login # replace with simatic-ax/actions/apax-login@v3
        with:
          apax-token: ${{ secrets.APAX_TOKEN }}
          registries: |
            https://npm.pkg.github.com/,${{ secrets.DEPLOY_TOKEN }}
            
      - name: Publish apax package
        uses: ./apax-publish # replace with simatic-ax/actions/apax-publish@v3
        with:
          registries: |
            https://npm.pkg.github.com
          tag: latest
          path: actions-test # remove later, for test purposes only