name: release-library
on:
  workflow_call:
    secrets:
      APAX_TOKEN:
        description: "Access token for installing apax sdk"
        required: true
env:
  ACTION_REPO_PATH: ./actions
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout actions repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: "Checkout actions repository"
        uses: actions/checkout@v3
        with:
          repository: simatic-ax/actions
          ref: "kruegerf-feat-reusable"
          fetch-depth: 1
          path: actions

      - name: "Setup the apax runner"
        uses: ./actions/.github/actions/setup-apax-runner

      - name: "Build the apax workspace"
        uses: ./actions/.github/actions/build-apax-package
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Test apax artifact"
        uses: ./actions/.github/actions/test-apax-package

      - name: "Release apax library"
        uses: ./actions/.github/actions/
