name: release-library
on:
  workflow_call:
    secrets:
      APAX_TOKEN:
        description: "Access token for installing apax sdk"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup the apax runner"
        uses: ./.github/actions/setup-apax-runner

      - name: "checkout repo"
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0

      - name: "Build the apax workspace"
        uses: ./.github/actions/build-apax-package
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Test apax artifact"
        uses: ./.github/actions/test-apax-package

      - name: "Release apax library"
        uses: ./.github/actions/
