# This workflow creates a template based of the repository and publishes it to the registry
name: Templatify workflow
env:
  TEMPLATE_DIRECTORY_NAME: working-directory # adapt later to your specific needs
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the template package itself"
        required: true
permissions:
  packages: read
  
jobs:
  templatify:
    name: Templatify
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.5.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Templatify repository
        uses: ./apax-templatify # replace with simatic-ax/actions/apax-templatify@v3
        with:
          path: actions-test # remove later, only here for test purposes
          version:  ${{ inputs.version }}
          working-directory: ${{ env.TEMPLATE_DIRECTORY_NAME }}

      - name: Pack the template
        uses: ./apax-pack # simatic-ax/actions/apax-pack@v3
        with:
          path: actions-test/${{ env.WORKING_DIR }} # adapt later to your specific needs
          version: ${{ inputs.version }}
      
      - name: Login to required registries
        uses: ./apax-login # replace with simatic-ax/actions/apax-login@v3
        with:
          apax-token: ${{ secrets.APAX_TOKEN }}
          registries: |
            https://npm.pkg.github.com/,${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish template
        uses: ./apax-publish # simatic-ax/actions/apax-publish@v3
        with:
          registries: |
            https://npm.pkg.github.com/
          tag:  ${{ inputs.version }}
          path: actions-test/${{ env.WORKING_DIR }} # adapt later to your specific needs
