
name: Templatify workflow

on:
  workflow_dispatch:
    inputs:
      repository-url:
        description: "The URL of the repository to templatify"
        required: true

jobs:
  templatify:
    name: Templatify
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.4.2
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Templatify repository
        uses: ./apax-templatify # replace with simatic-ax/actions/apax-templatify@v3
        with:
          path: actions-test # remove later, only here for test purposes

      

