name: Test actions workflow

on:
    push:
      branches:
        - 'main'
        - 'main/**'
    pull_request:
      branches:
        - 'main'
        - 'main/**'

jobs:
    call-apax-login-tests:
        name: Execute apax-login tests
        uses: ./.github/workflows/apax-login-tests-workflow.yml
        secrets:
            APAX_TOKEN: ${{ secrets.APAX_TOKEN }}
            DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}