name: Manual Trigger of Distribute Common Files
# For more information check distribute-common-files

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: Comma-separated list of file paths or directories to replicate. Like "files/libraries/workflows/release-library.yml"
        required: true
        type: string
      target_path:
        description: Target path where files will be copied. In the format ".github/workflows".
        required: true
        type: string
      repos_to_ignore:
        description: Comma-separated list of repositories to ignore.
        required: false
        type: string
      topics_to_include:
        description: Comma-separated list of topics / tags to include repositories.
        required: false
        type: string

jobs:
  run-distribute-common-files:
    runs-on: ubuntu-latest
    steps:
      - name: Run Distribute Common Files Action
        uses: ./distribute-common-files
        with:
          file_name: ${{ inputs.file_name }}
          target_path: ${{ inputs.target_path }}
          repos_to_ignore: ${{ inputs.repos_to_ignore }}
          topics_to_include: ${{ inputs.topics_to_include }}
